import SwiftUI
import UIKit

struct MyDynamicsView: View {
    @StateObject private var model = MyDynamicsViewModel()
    var body: some View {
        ZStack { Color(.systemGroupedBackground).ignoresSafeArea(); ScrollView { LazyVStack(spacing: 14) { ForEach(model.items) { item in NavigationLink { DynamicDetailView(blog: item) } label: { card(item) }.buttonStyle(.plain) }.padding() }; if let error = model.errorMessage { Text(error).font(.footnote).foregroundStyle(.red).padding(.horizontal) } } }
            .navigationTitle("我的动态").navigationBarTitleDisplayMode(.inline).task { await model.load() }.refreshable { await model.load() }
    }
    private func card(_ item: BlogPageResponse) -> some View { VStack(alignment: .leading, spacing: 10) { Text(item.pushTime ?? "").font(.caption).foregroundStyle(.secondary); if let c=item.content,!c.isEmpty { Text(c) }; if let imgs=item.images,!imgs.isEmpty { ForEach(imgs,id:\.self){ DynamicImageView(urlString:$0) } }; HStack { Label("\(item.fabulous ?? 0)",systemImage:"heart"); Label("\(item.comment ?? 0)",systemImage:"message") }.font(.footnote).foregroundStyle(.secondary) }.padding().frame(maxWidth:.infinity,alignment:.leading).background(Color(.secondarySystemBackground)).clipShape(RoundedRectangle(cornerRadius:14)) }
}

struct DynamicDetailView: View {
    let blog: BlogPageResponse
    @Environment(\.dismiss) private var dismiss
    @StateObject private var model = DynamicDetailViewModel()
    @FocusState private var inputFocused: Bool
    @State private var actionError: String?
    var body: some View {
        VStack(spacing: 0) {
            ScrollView {
                VStack(alignment: .leading, spacing: 14) {
                    HStack { RemoteAvatar(urlString:blog.headPortrait,size:48); VStack(alignment:.leading){Text(blog.nickName ?? "用户").font(.headline);Text(blog.pushTime ?? "").font(.caption).foregroundStyle(.secondary)}; Spacer(); Menu { Button("删除动态",role:.destructive){Task{do{try await model.delete(blog); UserDefaults.standard.removeObject(forKey:"friend.user.dynamics.cache"); dismiss()}catch{actionError=error.localizedDescription}}} } label:{Image(systemName:"ellipsis")} }
                    if let c=blog.content,!c.isEmpty { Text(c) }
                    if let imgs=blog.images,!imgs.isEmpty { ForEach(imgs,id:\.self){ image in DynamicImageView(urlString:image) } }
                    HStack { Button { Task { do { try await model.toggleLike(blog) } catch { actionError = error.localizedDescription } } } label:{Label("\(model.likeCount)",systemImage:model.liked ? "heart.fill":"heart")}; Spacer() }.foregroundStyle(model.liked ? .red:.secondary)
                    Divider(); Text("评论").font(.headline)
                    ForEach(model.comments){ comment in CommentRow(comment:comment,currentUserId:model.currentUserId,blogOwnerId:blog.userId,onTap:{model.replyTarget=comment;inputFocused=true},onDelete:{id in Task{do{try await model.deleteComment(id:id,blogId:blog.id)}catch{actionError=error.localizedDescription}}}) }
                }.padding()
            }
            .contentShape(Rectangle())
            .simultaneousGesture(DragGesture().onChanged { _ in inputFocused = false })
            HStack { TextField(model.replyTarget == nil ? "写评论" : "回复 \(model.replyTarget?.nickName ?? "评论")",text:$model.commentText).textFieldStyle(.roundedBorder).focused($inputFocused); Button("发送"){Task{await model.submit(blogId:blog.id);inputFocused=false}} }.padding()
            if let actionError { Text(actionError).font(.footnote).foregroundStyle(.red).padding(.bottom, 4) }
            if let submitError = model.submitError { Text(submitError).font(.footnote).foregroundStyle(.red).padding(.bottom, 4) }
        }.contentShape(Rectangle()).simultaneousGesture(TapGesture().onEnded{inputFocused=false}).navigationTitle("动态详情").navigationBarTitleDisplayMode(.inline).task{await model.load(blog:blog)}
    }
}

struct CommentRow: View { let comment:CommentItem; let currentUserId:Int?; let blogOwnerId:Int?; let onTap:()->Void; let onDelete:(Int)->Void; @State private var showMenu=false; @State private var deleteId:Int?; var isMine:Bool { currentUserId != nil && comment.userId == currentUserId }; var canDeleteAll:Bool { blogOwnerId != nil && currentUserId == blogOwnerId }; var body:some View { VStack(alignment:.leading,spacing:8){HStack{RemoteAvatar(urlString:comment.headPortrait,size:36);VStack(alignment:.leading){Text(comment.nickName ?? "用户").font(.subheadline.bold()).foregroundStyle(.secondary);Text(comment.content ?? "");Text("\(comment.pushTime ?? "")  IP：\(comment.city ?? LocationRefreshService.shared.cachedCity ?? "未知")").font(.caption).foregroundStyle(.secondary)};Spacer();if isMine || canDeleteAll{trashButton(comment.id)}};if !comment.allReplies.isEmpty{ForEach(comment.allReplies,id:\.id){reply in HStack{Text("\(reply.nickName ?? "用户") 回复：\(reply.content ?? "")").font(.caption).foregroundStyle(.secondary);Spacer();if currentUserId != nil && (reply.userId == currentUserId || canDeleteAll){trashButton(reply.id)}}.padding(.leading,46)}}}.padding(.vertical,10).overlay(alignment:.bottom){Divider()}.contentShape(Rectangle()).onTapGesture{onTap()}.onLongPressGesture{showMenu=true}.confirmationDialog("评论操作",isPresented:$showMenu){Button("复制"){UIPasteboard.general.string=comment.content ?? ""};Button("举报"){};Button("取消",role:.cancel){}}.alert("确认删除",isPresented:Binding(get:{deleteId != nil},set:{if !$0{deleteId=nil}})){Button("删除",role:.destructive){if let id=deleteId{onDelete(id)};deleteId=nil};Button("取消",role:.cancel){deleteId=nil}}}; @ViewBuilder private func trashButton(_ id:Int)->some View{Button{deleteId=id}label:{Image(systemName:"trash.fill").foregroundStyle(.red)}} }

@MainActor final class DynamicDetailViewModel:ObservableObject { @Published var comments:[CommentItem]=[]; @Published var commentText=""; @Published var liked=false; @Published var likeCount=0; @Published var replyTarget:CommentItem?; @Published var submitError:String?; var currentUserId:Int?{guard let d=UserDefaults.standard.data(forKey:"friend.user.center.cache"),let p=try? JSONDecoder().decode(PersonalCenter.self,from:d)else{return nil};return p.id}; func load(blog:BlogPageResponse)async{likeCount=blog.fabulous ?? 0;liked=blog.thumbsUp ?? false;await loadComments(blog.id)}; func loadComments(_ id:Int)async{do{let r:APIEnvelope<PageResult<CommentItem>>=try await APIClient.shared.request(path:"community/frblog/blog/comment/page/\(id)",method:"GET",body:CommentsQuery(pageIndex:1,pageSize:100));comments=r.data?.rows ?? []}catch{}}; func toggleLike(_ blog:BlogPageResponse)async throws{let r:APIEnvelope<EmptyResponse>=try await APIClient.shared.request(path:"community/frblog/like/\(blog.id)",method:"POST",body:EmptyBody());guard r.code == 200 else{throw APIError(statusCode:r.code,message:r.msg ?? "点赞失败")};let updated:APIEnvelope<PageResult<BlogPageResponse>>=try await APIClient.shared.request(path:"community/frblog/mine/blog/page",method:"GET",body:MyDynamicsPageQuery(pageIndex:1,pageSize:20));if let current=updated.data?.rows.first(where:{$0.id==blog.id}){liked=current.thumbsUp ?? false;likeCount=current.fabulous ?? 0}else{throw APIError(statusCode:nil,message:"点赞后刷新动态失败")}}; func submit(blogId:Int)async{let t=commentText.trimmingCharacters(in:.whitespacesAndNewlines);guard !t.isEmpty else{return};do{let r:APIEnvelope<EmptyResponse>=try await APIClient.shared.request(path:"community/frblog/blog/comment/\(blogId)",method:"POST",body:CommentRequest(content:t,parentId:replyTarget?.id,replyId:replyTarget?.userId));guard r.code == 200 else{throw APIError(statusCode:r.code,message:r.msg ?? "发送评论失败")};commentText="";replyTarget=nil;await loadComments(blogId)}catch{submitError=error.localizedDescription}}; func deleteComment(id:Int,blogId:Int)async throws{let r:APIEnvelope<EmptyResponse>=try await APIClient.shared.request(path:"community/frblog/blog/comment/delete/\(id)",method:"POST",body:EmptyBody());guard r.code == 200 else{throw APIError(statusCode:r.code,message:r.msg ?? "删除评论失败")};await loadComments(blogId)}; func delete(_ blog:BlogPageResponse)async throws{let r:APIEnvelope<EmptyResponse>=try await APIClient.shared.request(path:"community/frblog/\(blog.id)",method:"DELETE",body:EmptyBody());guard r.code == 200 else{throw APIError(statusCode:r.code,message:r.msg ?? "删除动态失败")}} }

@MainActor final class MyDynamicsViewModel:ObservableObject{ @Published var items:[BlogPageResponse]=[]; @Published var errorMessage:String?; func load() async { do { let r: APIEnvelope<PageResult<BlogPageResponse>> = try await APIClient.shared.request(path:"community/frblog/mine/blog/page", method:"GET", body:MyDynamicsPageQuery(pageIndex:1,pageSize:20)); guard let rows = r.data?.rows else { throw APIError(statusCode:nil,message:r.msg ?? "动态数据为空") }; items = rows; errorMessage=nil } catch { errorMessage=error.localizedDescription } } }
struct MyDynamicsPageQuery:Encodable{let pageIndex:Int;let pageSize:Int}; struct CommentItem:Decodable,Identifiable{let id:Int;let userId:Int?;let content:String?;let nickName:String?;let headPortrait:String?;let pushTime:String?;let city:String?;let replyId:Int?;let replyList:[CommentItem]?;let replies:[CommentItem]?;var allReplies:[CommentItem]{replyList ?? replies ?? []}}; struct CommentsQuery:Encodable{let pageIndex:Int;let pageSize:Int}; struct CommentRequest:Encodable{let content:String;let parentId:Int?;let replyId:Int?}
