import SwiftUI

struct MyDynamicsView: View {
    @StateObject private var model = MyDynamicsViewModel()
    var body: some View { ZStack{Color(.systemGroupedBackground).ignoresSafeArea();ScrollView{LazyVStack(spacing:14){ForEach(model.items){ item in
                NavigationLink { DynamicDetailView(blog: item) } label: { card(item) }
                    .buttonStyle(.plain)
            }}.padding()}}.navigationTitle("我的动态").navigationBarTitleDisplayMode(.inline).task{await model.load()}.refreshable{await model.load()} }
    private func card(_ item: BlogPageResponse)->some View { VStack(alignment:.leading,spacing:10){Text(item.pushTime ?? "").font(.caption).foregroundStyle(.secondary);if let c=item.content,!c.isEmpty{Text(c).font(.body)};if let imgs=item.images,!imgs.isEmpty{ForEach(imgs,id:\.self){RemoteAvatar(urlString:$0,size:180)}};HStack{Label("\(item.fabulous ?? 0)",systemImage:"heart");Label("\(item.comment ?? 0)",systemImage:"message")}.font(.footnote).foregroundStyle(.secondary)}.padding().frame(maxWidth:.infinity,alignment:.leading).background(Color(.secondarySystemBackground)).clipShape(RoundedRectangle(cornerRadius:14))}
}

struct DynamicDetailView: View {
    let blog: BlogPageResponse
    @StateObject private var model = DynamicDetailViewModel()
    var body: some View { VStack(spacing:0){ScrollView{VStack(alignment:.leading,spacing:14){HStack{RemoteAvatar(urlString:blog.headPortrait,size:48);VStack(alignment:.leading){Text(blog.nickName ?? "用户").font(.headline);Text(blog.pushTime ?? "").font(.caption).foregroundStyle(.secondary)};Spacer();Menu{Button("删除动态",role:.destructive){Task{await model.delete(blog)}}}label:{Image(systemName:"ellipsis")}};if let c=blog.content,!c.isEmpty{Text(c).font(.body)};if let imgs=blog.images,!imgs.isEmpty{ForEach(imgs,id:\.self){RemoteAvatar(urlString:$0,size:260)}};HStack{Button{Task{await model.toggleLike(blog)}}label:{Label("\(model.likeCount)",systemImage:model.liked ? "heart.fill":"heart")};Spacer()}.foregroundStyle(model.liked ? .red:.secondary);Divider();Text("评论").font(.headline);ForEach(model.comments){comment in CommentRow(comment:comment){model.replyTarget=comment}}}.padding()};HStack{TextField(model.replyTarget == nil ? "写评论" : "回复 \(model.replyTarget?.nickName ?? "评论")",text:$model.commentText).textFieldStyle(.roundedBorder);Button("发送"){Task{await model.submit(blogId:blog.id)}}}.padding()}.navigationTitle("动态详情").navigationBarTitleDisplayMode(.inline).task{await model.load(blog:blog)} }
}

struct CommentRow: View { let comment: CommentItem; let onReply:()->Void; var body: some View { VStack(alignment:.leading,spacing:8){HStack{RemoteAvatar(urlString:comment.headPortrait,size:36);VStack(alignment:.leading){Text(comment.nickName ?? "用户").font(.subheadline.bold());Text(comment.content ?? "");Text("\(comment.pushTime ?? "")  地区：\(comment.city ?? "未知")").font(.caption).foregroundStyle(.secondary)};Spacer()};Button("回复"){onReply()}.font(.caption);if let replies=comment.replies{ForEach(replies){reply in Text("\(reply.nickName ?? "用户"): \(reply.content ?? "")").font(.caption).padding(.leading,44)}}}.padding(.vertical,10).overlay(alignment:.bottom){Divider()} }
}

@MainActor final class DynamicDetailViewModel: ObservableObject { @Published var comments:[CommentItem]=[];@Published var commentText="";@Published var liked=false;@Published var likeCount=0;@Published var replyTarget:CommentItem?;func load(blog:BlogPageResponse)async{likeCount=blog.fabulous ?? 0;liked=blog.thumbsUp ?? false;await loadComments(blog.id)};func loadComments(_ id:Int)async{do{let r:APIEnvelope<PageResult<CommentItem>>=try await APIClient.shared.request(path:"community/frblog/blog/comment/page/\(id)",method:"GET",body:CommentsQuery(pageIndex:1,pageSize:100));comments=r.data?.rows ?? []}catch{}};func toggleLike(_ blog:BlogPageResponse)async{let _:APIEnvelope<EmptyResponse>?=try? await APIClient.shared.request(path:"community/frblog/like/\(blog.id)",method:"POST",body:EmptyBody());liked.toggle();likeCount += liked ? 1 : -1;await loadComments(blog.id)};func submit(blogId:Int)async{let text=commentText.trimmingCharacters(in:.whitespacesAndNewlines);guard !text.isEmpty else{return};let _:APIEnvelope<EmptyResponse>?=try? await APIClient.shared.request(path:"community/frblog/blog/comment/\(blogId)",method:"POST",body:CommentRequest(content:text,parentId:replyTarget?.id,replyId:replyTarget?.userId));commentText="";replyTarget=nil;await loadComments(blogId)};func delete(_ blog:BlogPageResponse)async{let _:APIEnvelope<EmptyResponse>?=try? await APIClient.shared.request(path:"community/frblog/\(blog.id)",method:"DELETE",body:EmptyBody())}}

@MainActor final class MyDynamicsViewModel:ObservableObject{@Published var items:[BlogPageResponse]=[];func load()async{do{let r:APIEnvelope<PageResult<BlogPageResponse>>=try await APIClient.shared.request(path:"community/frblog/mine/blog/page",method:"GET",body:MyDynamicsPageQuery(pageIndex:1,pageSize:20));items=r.data?.rows ?? []}catch{items=[]}}}
struct MyDynamicsPageQuery:Encodable{let pageIndex:Int;let pageSize:Int}
struct CommentItem:Decodable,Identifiable{let id:Int;let userId:Int?;let content:String?;let nickName:String?;let headPortrait:String?;let pushTime:String?;let city:String?;let replies:[CommentItem]?}
struct CommentsQuery:Encodable{let pageIndex:Int;let pageSize:Int}
struct CommentRequest:Encodable{let content:String;let parentId:Int?;let replyId:Int?}
