import Foundation
import SwiftUI
import CoreLocation

@MainActor final class RegisterViewModel: NSObject, ObservableObject, CLLocationManagerDelegate {
    @Published var phone=""; @Published var code=""; @Published var gender="male"; @Published var nickname=""; @Published var birthday=""; @Published var city=""; @Published var cityCode="0"; @Published var latitude=""; @Published var longitude=""; @Published var password=""; @Published var confirmPassword=""; @Published var avatarData:Data?; @Published var isLoading=false; @Published var errorMessage:String?; @Published var stage=1; @Published var isLocating=false
    private let locationManager = CLLocationManager()
    private let geocoder = CLGeocoder()
    override init() { super.init(); locationManager.delegate = self; locationManager.desiredAccuracy = kCLLocationAccuracyHundredMeters }
    func requestLocation() { guard CLLocationManager.locationServicesEnabled() else { errorMessage="系统定位服务未开启，请手动填写城市"; return }; isLocating=true; locationManager.requestWhenInUseAuthorization(); locationManager.startUpdatingLocation() }
    func locationManagerDidChangeAuthorization(_ manager: CLLocationManager) { if manager.authorizationStatus == .denied || manager.authorizationStatus == .restricted { isLocating=false; errorMessage="定位权限被拒绝，请手动填写城市" } else if manager.authorizationStatus == .authorizedWhenInUse || manager.authorizationStatus == .authorizedAlways { manager.startUpdatingLocation() } }
    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) { guard let location=locations.last else{return}; latitude=String(location.coordinate.latitude); longitude=String(location.coordinate.longitude); manager.stopUpdatingLocation(); geocoder.reverseGeocodeLocation(location){[weak self] places,error in Task { @MainActor in guard let self else{return}; self.isLocating=false; if let place=places?.first { self.city = place.locality ?? place.administrativeArea ?? self.city; self.cityCode = place.isoCountryCode == "CN" ? (place.administrativeArea ?? "0") : "0" } else if let error { self.errorMessage=error.localizedDescription } } } }
    func locationManager(_ manager: CLLocationManager, didFailWithError error: Error) { isLocating=false; errorMessage="无法获取定位，请手动填写城市" }
    func verifyCode() async { guard !phone.isEmpty,!code.isEmpty else { errorMessage="请输入手机号和验证码"; return }; do { let _:APIEnvelope<EmptyResponse> = try await APIClient.shared.request(path:"token/checksms",method:"POST",body:["messageType":"REGISTER","phone":phone,"code":code]); stage=2; requestLocation() } catch { errorMessage=error.localizedDescription } }
    func register() async -> Bool { guard !nickname.isEmpty,!birthday.isEmpty,!city.isEmpty,!password.isEmpty,password==confirmPassword else { errorMessage="请完整填写资料并确认密码"; return false }; isLoading=true; defer{isLoading=false}; do { var avatarURL:String?; if let data=avatarData { avatarURL=try await APIClient.shared.uploadFile(data:data,filename:"avatar.jpg",mimeType:"image/jpeg").data?.url }; let body=RegisterRequest(headPortrait:avatarURL,phone:phone,code:code,nickName:nickname,birthday:birthday,lat:latitude,lon:longitude,city:city,gender:gender,verificationCode:code,password:password,truePassword:confirmPassword,cityCode:cityCode); let _:APIEnvelope<EmptyResponse>=try await APIClient.shared.request(path:"token/register",method:"POST",body:body,token:nil); let login:APIEnvelope<LoginResponse>=try await APIClient.shared.request(path:"token/login",method:"POST",body:LoginRequest(username:phone,password:password),token:nil); guard let token=login.data?.token,!token.isEmpty else { throw APIError(statusCode:nil,message:"注册成功但自动登录缺少 Token") }; TokenStore.shared.token=token; return true } catch { errorMessage=error.localizedDescription; return false } }
}

struct ImagePicker: UIViewControllerRepresentable { @Binding var data:Data?; func makeCoordinator()->Coordinator{Coordinator(self)}; func makeUIViewController(context:Context)->UIImagePickerController{let p=UIImagePickerController();p.sourceType = .photoLibrary;p.delegate=context.coordinator;return p};func updateUIViewController(_ uiViewController:UIImagePickerController,context:Context){};final class Coordinator:NSObject,UINavigationControllerDelegate,UIImagePickerControllerDelegate{let parent:ImagePicker;init(_ parent:ImagePicker){self.parent=parent};func imagePickerController(_ picker:UIImagePickerController,didFinishPickingMediaWithInfo info:[UIImagePickerController.InfoKey:Any]){if let image=info[.originalImage] as? UIImage{parent.data=image.jpegData(compressionQuality:0.82)};picker.dismiss(animated:true)}}}
