import SwiftUI

struct UserCenterView: View {
    @StateObject private var model = UserCenterViewModel()
    @StateObject private var dynamics = UserCenterDynamicsViewModel()
    @State private var showLogin = false
    @State private var cachedCity: String?
    @State private var hasCheckedSession = false
    let topSafeArea: CGFloat?
    private let designWidth: CGFloat = 750
    private func px(_ r: CGFloat, _ w: CGFloat) -> CGFloat { w * r / designWidth }
    var body: some View {
        GeometryReader { proxy in
            let w = proxy.size.width
            ZStack { Image("FriendUserIndex").resizable().scaledToFill().ignoresSafeArea(); Color.black.opacity(0.1).ignoresSafeArea(); ScrollView(showsIndicators: false) { VStack(spacing: 0) { Color.clear.frame(height: (topSafeArea ?? proxy.safeAreaInsets.top) + px(24, w)); topBar(width: w); if let info = model.userInfo { profile(info, width: w); dynamicList(width: w) } else if hasCheckedSession { Button("请登录") { showLogin = true }.foregroundStyle(.white).padding(.top, 100) } else { ProgressView().tint(.white).padding(.top, 100) }; Color.clear.frame(height: 120) }.padding(.horizontal, px(32, w)) }.refreshable { await refreshAll() } }
        }.navigationTitle("").navigationBarHidden(true).sheet(isPresented: $showLogin) { NavigationView { LoginView() } }.task { cachedCity = LocationRefreshService.shared.cachedCity; await loadAll() }.onReceive(NotificationCenter.default.publisher(for: .locationCityUpdated)) { note in cachedCity = note.object as? String }
    }
    private func loadAll() async { await model.loadIfNeeded(); dynamics.loadIfNeeded(); do { if dynamics.items.isEmpty { try await dynamics.load() } } catch { dynamics.errorMessage = error.localizedDescription }; hasCheckedSession = true }
    private func refreshAll() async { await model.refresh(); do { try await dynamics.load() } catch { dynamics.errorMessage = error.localizedDescription } }
    private func topBar(width w: CGFloat) -> some View { HStack { HStack(spacing: 0) { Button { } label: { ProfileActionIcon(kind: .pencil) }.frame(width: px(38, w), height: px(38, w)); Spacer(); HStack(spacing: px(40, w)) { Button { } label: { ProfileActionIcon(kind: .footprints).frame(width: px(38, w), height: px(38, w)) }; Button { } label: { ProfileActionIcon(kind: .addPerson).frame(width: px(38, w), height: px(38, w)) }; NavigationLink { UserSettingsView() } label: { ProfileActionIcon(kind: .menu).frame(width: px(38, w), height: px(38, w)) } }.frame(height: px(60, w)) }.font(.system(size: px(32, w), weight: .medium)).foregroundStyle(Color(white: 0.96)).frame(height: px(60, w)) }.frame(height: px(52, w)) }
    private func profile(_ info: PersonalCenter, width w: CGFloat) -> some View { HStack(spacing: px(24, w)) { VStack(alignment: .leading, spacing: px(18, w)) { HStack(spacing: px(18, w)) { Text(info.nickName ?? "用户").font(.system(size: px(40, w), weight: .bold)).foregroundStyle(.white); Text(info.genderText).font(.system(size: px(25, w))).foregroundStyle(.pink); Text("IP：\(info.city ?? cachedCity ?? "未知")").font(.system(size: px(24, w))).foregroundStyle(.white.opacity(0.65)) }; HStack(spacing: px(32, w)) { statValue("\(info.followCount ?? 0)", "关注", w); statValue("\(info.fansCount ?? 0)", "粉丝", w); statValue("\(info.likeCount ?? 0)", "赞", w) } }; Spacer(minLength: 0); RemoteAvatar(urlString: info.headPortrait, size: px(140, w)) }.padding(.top, px(34, w)) }
    private func statValue(_ value: String, _ title: String, _ w: CGFloat) -> some View { VStack(alignment: .leading, spacing: 2) { Text(value).font(.system(size: px(28, w), weight: .bold)).foregroundStyle(.white); Text(title).font(.system(size: px(22, w))).foregroundStyle(.white.opacity(0.62)) } }
    private func dynamicList(width w: CGFloat) -> some View { VStack(alignment: .leading, spacing: 12) { Text("我的动态").font(.system(size: px(32, w), weight: .bold)).foregroundStyle(.white); if dynamics.items.isEmpty { if let error=dynamics.errorMessage { Text(error).font(.system(size: px(24, w))).foregroundStyle(.red) } else { Text("暂无动态").font(.system(size: px(24, w))).foregroundStyle(.white.opacity(0.6)) } } else { ForEach(dynamics.items) { blogCard($0, w) } } }.padding(.top, px(54, w)).padding(.bottom, px(50, w)) }
    private func blogCard(_ blog: BlogPageResponse, _ w: CGFloat) -> some View { NavigationLink { DynamicDetailView(blog: blog) } label: { VStack(alignment: .leading, spacing: 10) { HStack { Text(blog.pushTime ?? "").font(.caption).foregroundStyle(.white.opacity(0.6)); Spacer() }; if let content = blog.content, !content.isEmpty { Text(content).font(.system(size: 16)).foregroundStyle(.white) }; if let images = blog.images { ForEach(images, id: \.self) { image in DynamicImageView(urlString: image) } }; HStack { Label("\(blog.fabulous ?? 0)", systemImage: "heart"); Label("\(blog.comment ?? 0)", systemImage: "message") }.font(.footnote).foregroundStyle(.white.opacity(0.75)) }.padding(14).frame(maxWidth: .infinity, alignment: .leading).background(Color.white.opacity(0.12)).clipShape(RoundedRectangle(cornerRadius: 16)) }.buttonStyle(.plain) }
}

@MainActor final class UserCenterDynamicsViewModel: ObservableObject {
    @Published var items: [BlogPageResponse] = []
    @Published var errorMessage: String?
    @Published var likeError: String?
    private let cacheKey = "friend.user.dynamics.cache"
    init() { if let data = UserDefaults.standard.data(forKey: cacheKey), let cached = try? JSONDecoder().decode([BlogPageResponse].self, from: data) { items = cached } }
    func loadIfNeeded() { guard items.isEmpty else { return } }
    func load() async throws { let r: APIEnvelope<PageResult<BlogPageResponse>> = try await APIClient.shared.request(path: "community/frblog/mine/blog/page", method: "GET", body: UserCenterPageQuery(pageIndex: 1, pageSize: 100)); guard let rows = r.data?.rows else { throw APIError(statusCode: nil, message: r.msg ?? "动态数据为空") }; items = rows; UserDefaults.standard.removeObject(forKey: cacheKey); if let data = try? JSONEncoder().encode(rows) { UserDefaults.standard.set(data, forKey: cacheKey) }; errorMessage = nil }
    func toggleLike(_ item: BlogPageResponse) async throws { let r: APIEnvelope<EmptyResponse> = try await APIClient.shared.request(path: "community/frblog/like/\(item.id)", method: "POST", body: EmptyBody()); guard r.code == 200 else { throw APIError(statusCode: r.code, message: r.msg ?? "点赞失败") }; try await load() }
}
struct UserCenterPageQuery: Encodable { let pageIndex: Int; let pageSize: Int }
@MainActor final class UserCenterViewModel: ObservableObject { @Published var userInfo: PersonalCenter?; @Published var errorMessage: String?; private static let cacheKey = "friend.user.center.cache"; func loadIfNeeded() async { guard TokenStore.shared.token != nil else { return }; if userInfo == nil, let data = UserDefaults.standard.data(forKey: Self.cacheKey), let cached = try? JSONDecoder().decode(PersonalCenter.self, from: data) { userInfo = cached }; guard userInfo == nil else { return }; await load(force: true) }; func load(force: Bool = false) async { guard TokenStore.shared.token != nil else { return }; if !force, userInfo != nil { return }; do { let r: APIEnvelope<PersonalCenter> = try await APIClient.shared.request(path: "community/fruser/personalCenter", method: "GET", body: EmptyBody()); guard let info = r.data else { throw APIError(statusCode: r.code, message: r.msg ?? "个人资料为空") }; userInfo = info; if let data = try? JSONEncoder().encode(info) { UserDefaults.standard.set(data, forKey: Self.cacheKey) } } catch { errorMessage = error.localizedDescription } }; func refresh() async { await load(force: true) } }
struct PersonalCenterBlog: Codable, Identifiable { let image: String?; let content: String?; let time: String?; private let idValue: Int; var id: Int { idValue }; enum CodingKeys: String, CodingKey { case id, image, content, time }; init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let id = try c.decodeIfPresent(Int.self, forKey: .id); image = try c.decodeIfPresent(String.self, forKey: .image); content = try c.decodeIfPresent(String.self, forKey: .content); time = try c.decodeIfPresent(String.self, forKey: .time); idValue = id ?? content?.hashValue ?? 0 }; func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); try c.encode(idValue, forKey: .id); try c.encodeIfPresent(image, forKey: .image); try c.encodeIfPresent(content, forKey: .content); try c.encodeIfPresent(time, forKey: .time) } }
struct PersonalCenter: Codable { let id: Int?; let headPortrait: String?; let nickName: String?; let gender: String?; let goldBalance: Int?; let city: String?; let blogCount: Int?; let followCount: Int?; let fansCount: Int?; let likeCount: Int?; let blog: [PersonalCenterBlog]?; var genderText: String { gender == "WOMAN" || gender == "女" ? "♀" : gender == "MAN" || gender == "男" ? "♂" : "" } }
